import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ShoppingCart, Trash2, Plus, Minus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger, } from "@/components/ui/sheet";
import { useCart } from "@/contexts/CartContext";
import { useNavigate } from "react-router-dom";
const Cart = () => {
    const { items, removeItem, updateQuantity, total, itemCount, clearCart } = useCart();
    const navigate = useNavigate();
    return (_jsxs(Sheet, { children: [_jsx(SheetTrigger, { asChild: true, children: _jsxs(Button, { variant: "outline", size: "icon", className: "relative", children: [_jsx(ShoppingCart, { className: "h-5 w-5" }), itemCount > 0 && (_jsx("span", { className: "absolute -top-2 -right-2 bg-primary text-primary-foreground rounded-full h-6 w-6 flex items-center justify-center text-xs font-bold", children: itemCount }))] }) }), _jsxs(SheetContent, { className: "w-full sm:max-w-lg", children: [_jsx(SheetHeader, { children: _jsx(SheetTitle, { children: "Seu Carrinho" }) }), items.length === 0 ? (_jsxs("div", { className: "flex flex-col items-center justify-center h-[calc(100vh-200px)] text-center", children: [_jsx(ShoppingCart, { className: "h-24 w-24 text-muted-foreground/20 mb-4" }), _jsx("p", { className: "text-muted-foreground", children: "Seu carrinho est\u00E1 vazio" })] })) : (_jsxs("div", { className: "flex flex-col h-[calc(100vh-120px)]", children: [_jsx("div", { className: "flex-1 overflow-auto py-4 space-y-4", children: items.map((item) => (_jsxs("div", { className: "flex gap-4 p-4 rounded-lg border border-border/40 bg-card/50", children: [_jsxs("div", { className: "flex-1", children: [_jsx("h4", { className: "font-semibold text-foreground", children: item.nome }), _jsx("p", { className: "text-sm text-muted-foreground", children: item.categoria }), _jsxs("p", { className: "text-lg font-bold text-primary mt-2", children: ["R$ ", (item.preco * item.quantidade).toFixed(2)] })] }), _jsxs("div", { className: "flex flex-col gap-2", children: [_jsxs("div", { className: "flex items-center gap-2 bg-muted/50 rounded-md p-1", children: [_jsx(Button, { variant: "ghost", size: "icon", className: "h-6 w-6", onClick: () => updateQuantity(item.id, item.quantidade - 1), children: _jsx(Minus, { className: "h-3 w-3" }) }), _jsx("span", { className: "w-8 text-center font-semibold", children: item.quantidade }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-6 w-6", onClick: () => updateQuantity(item.id, item.quantidade + 1), children: _jsx(Plus, { className: "h-3 w-3" }) })] }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 text-destructive hover:text-destructive", onClick: () => removeItem(item.id), children: _jsx(Trash2, { className: "h-4 w-4" }) })] })] }, item.id))) }), _jsxs("div", { className: "border-t border-border/40 pt-4 space-y-4", children: [_jsxs("div", { className: "flex justify-between items-center text-xl font-bold", children: [_jsx("span", { children: "Total:" }), _jsxs("span", { className: "text-primary", children: ["R$ ", total.toFixed(2)] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Button, { className: "w-full bg-gradient-to-r from-primary to-accent hover:opacity-90", size: "lg", onClick: () => navigate("/checkout"), children: "Finalizar Pedido" }), _jsx(Button, { variant: "outline", className: "w-full", onClick: clearCart, children: "Limpar Carrinho" })] })] })] }))] })] }));
};
export default Cart;
//# sourceMappingURL=Cart.js.map